language: python
python:
    - "3.4"
script: pytest
deploy:
  provider: pypi
  on:
    tags: true
    branch: master
  user: Bookmark
  password:
    secure: 5wPiwRHSTxTdFNH/NiDjdQ+LF350baiwEWrJNRcLxa8ED66CuC6gDmkziRrSS+TRSqMJoLnqPaSsmOKT+q5lG2hYakwmSme+pzKTtAiz3nslqk6V93JdbPhnsTIhhHOt2YLRGHeWBMd5b7Ims00Uuml8N1Cg2+TkscWHgirvUQqStlbeC9pNvewpzBY7EArF4ixQ8i1mdzLoiajnYIRjZQwl+K11KEUvh8mplLIjl3wCZJu/fYR3ZVyJrQ28IKy1XWk8nLJRbSekwsbt0jJh2X+OsCVTxNlTqBT1WDvOppN4/0kDOQY2QRN/KAZWI5/R6a4GpgSaN0oOssnDwPNuZwgKZ1qMlRr/7bS5JShyz7jVvYH7k0tUwWiDn+TIlIj7QyibHKTtQRpRnewi5CAy/uToC/Bi+daC8bhfNOoXkzC9LLu6wh0nALZ+XLh/bKmv3jdmKY0ACX85JBikYh+/kUYWHowQjKJtU8b7A1+kGfN7i9zWt4JYOi/QoWTMXlU1sSmsvaoWo3RUL8nTI9AgGKHqjAv9r2v86geqFlr/QR3/UC8tYm47oQl3Uhd9IDzjPzHBIPLgZz+vDogXn/TZj2q0XUEQMTqKqoZ8QJBqMbgWlYup3fdvNM3S15xTWS7/tkJA3hmZLwTg2pzxPU+7om678m/ier5AbYSlevrJwRE
